### ISSUE TITLE
Research Summary: Liquidity risks in the decentralized finance protocol Aave

### ISSUE THREAD

**Issue by Siemingfong** [smartcontractresearchforum/research_content#146]
Research Pulse Issue #20 07/06/21:
https://www.smartcontractresearch.org/t/research-pulse-issue-20-07-06-21/550

Published Link:
https://www.smartcontractresearch.org/t/research-summary-liquidity-risks-in-the-decentralized-finance-protocol-aave/1062

Summary Link: https://docs.google.com/document/d/1wVKk-3P6DOz-9yAJBBbZrW_cBT5V4ffo81Sj2HnFGGg/edit?usp=sharing

**Comment by Siemingfong** [comment]
I'm almost done with the summary. Stating to review it.

**Comment by jamesmcgirk** [comment]
@cipherix ready for peer review! It's an economics paper about liquidity risk @cryptomarabout would this be something you'd like to review?

**Comment by Siemingfong** [comment]
@jamesmcgirk it's wonderful ideas, I would co-work with @Astridchou

**Comment by Siemingfong** [comment]
@jamesmcgirk I just finished the revision of the summary and add the Red Wednesday topic to this draft.

**Comment by jamesmcgirk** [comment]
@cryptomarabout ready for your peer review

**Comment by jamesmcgirk** [comment]
@Siemingfong is this one ready for Cipherex yet?

**Comment by Siemingfong** [comment]
@jamesmcgirk Yes, I finished the revision

**Comment by jamesmcgirk** [comment]
Moved over to FCR

**Comment by jamesmcgirk** [comment]
@cipherix ready for your review!

**Comment by cipherix** [comment]
Hey @Siemingfong -- could you resolve the comments? Also, do the comments on 'revision' require more work on your end?

**Comment by Siemingfong** [comment]
@cipherix Thanks! All the comments were addressed. The 'revision' means that I revision to my final version. It seems to easily let people misunderstand this note. I took it away.

**Comment by cipherix** [comment]
Great, thank you -- I will begin the review.

**Comment by Siemingfong** [comment]
@jamesmcgirk working on it.

**Comment by jamesmcgirk** [comment]
Moved back to FCR @Siemingfong because of questions raised by @lw-scrf

**Comment by Siemingfong** [comment]
@lw-scrf All the questions were answer, thanks for the review:)

**Comment by jamesmcgirk** [comment]
@cipherix @twan-dev should this one have another FCR check or is it okay for editorial / engagement?

**Comment by twan-dev** [comment]
@jamesmcgirk I think we're waiting for @lw-scrf to finish some checks & resolve ongoing discussions

**Comment by lw-scrf** [comment]
@twan-dev will move another review of this up on my scrf 'to do' list for tomorrow/Fri. will also create that shared doc for feedback and invite you and @jamesmcgirk.

**Comment by lw-scrf** [comment]
wanted to capture my note from 10.30.21 here, as i'm editing it out of the doc today, but i think it's important enough to capture. discord chat between @twan-dev @jamesmcgirk and i culminated in creation of a doc pipe feedback doc to help improve processes going forward. if anyone else wants to add feedback to it, permissions open to all scrf via this link: 
[(https://docs.google.com/document/d/1TUq1C7fSdoEhTL-jZUHtFPEezcjWlyaiXOYrmeU4GW0/edit?usp=sharing)]

This is my first read-through, 10.30.21, and I see several things already...I just wanted to bring the team's attention to this because the position in the doc pipe for this summary indicates that “Content” and “Editing” have already been done and the next step is “Publish”...will work on it (not sure I’ll catch everything though) and will bring up on Mon. GTM meeting...short story long, seems like this needs more eyes on it before publishing.

**Comment by lw-scrf** [comment]
wanted to add my comment from 10.30.21 here, since i'm editing it out of the doc today, but think it's important enough that it should be captured: 

This is my first read-through, 10.30.21, and I see several things already...I just wanted to bring the team's attention to this because the position in the doc pipe for this summary indicates that “Content” and “Editing” have already been done and the next step is “Publish”...will work on it (not sure I’ll catch everything though) and will bring up on Mon. GTM meeting...short story long, seems like this needs more eyes on it before publishing.

**Comment by lw-scrf** [comment]
@twan-dev @jamesmcgirk @Siemingfong 2nd pass done.

**Comment by jamesmcgirk** [comment]
Waiting for resolution before editorial review.

**Comment by jamesmcgirk** [comment]
@Siemingfong is this one ready for editorial review?

**Comment by Siemingfong** [comment]
@jamesmcgirk Definitely sure

**Comment by jamesmcgirk** [comment]
@Siemingfong @lw-scrf if everything is all good to go, I'll start my editorial review. GtM is already finished, unless there's anything either of you would like to add

**Comment by jamesmcgirk** [comment]
@lw-scrf is this one ready for editing yet?

**Comment by jamesmcgirk** [comment]
@Siemingfong @lw-scrf I went through this and made a few changes, please make sure that the Agent Behaviors section reflects LW's comments

**Comment by jamesmcgirk** [comment]
thanks for the fixes, @Siemingfong moved into engagement.

**Comment by Siemingfong** [comment]
It's published:
https://www.smartcontractresearch.org/t/research-summary-liquidity-risks-in-the-decentralized-finance-protocol-aave/1062
