### ISSUE TITLE
Research Summary: Multi-Layer Aggregate Verification for IoT Blockchain

### ISSUE THREAD

**Issue by SethAustinHarding** [smartcontractresearchforum/research_content#156]
Please check out my YouTube video that introduces this paper. https://www.youtube.com/watch?v=tbZV_hHguzg

**Comment by jamesmcgirk** [comment]
Have you started this one yet @Gearlad @Siemingfong ?

**Comment by Siemingfong** [comment]
@Gearlad @Siemingfong we start with this doc:
https://docs.google.com/document/d/1n7HEwmI96CYZA5P3hPzEPhPijADpXtQ23do70GHhA7U/edit?usp=sharing

**Comment by Gearlad** [comment]
@cipherix I just moved our MLAV paper to drafting

**Comment by jamesmcgirk** [comment]
@SethAustinHarding who is working on this one? Is it you and Sean or is it Yen Chih? (If it's the latter, I want him to go through the onboarding process before working on a summary)

**Comment by SethAustinHarding** [comment]
I'm working on it independently currently, but if @Siemingfong is interested he is more than welcome to join!

**Comment by jamesmcgirk** [comment]
Updates to the card - Proposed tags

AIoT Blockchain, Agriculture 4.0, Supply Chain Management, ID-based signature, batch verification, Android

Description of why this would be an interesting post
As part of the next stage of research for the AIoT Blockchain project, we would like to propose a paper that was co-authored by @Siemingfong and @SethAustinHarding 

The background of this paper is that in current agriculture 4.0, large companies have successfully applied blockchain solutions and ecosystems for tracking and tracing agricultural produce, achieving transparency, traceability, and digitalization. However, these blockchain solutions are not comprehensive.

Problem 1) The upstream nodes that these large companies serve are all large-scale production suppliers, and smallholders are not taken into consideration.
Problem 1 solution) We use a multi-layer architecture that serves three purposes: facilitating smallholders in joining the agricultural blockchain as equal-opportunity nodes, uploading of production activity data, and reducing costs (ex. Ethereum gas fee). We also design a blockchain management framework using smart contracts to facilitate the financing of upstream producers.

Problem 2) Most IoT blockchains adopt an ID-based signature scheme in IoT devices, which frequently has low efficiency.
Problem 2 solution) We use aggregate verification, effectively increasing ID-based verification efficiency while processing large clusters of data transferred by IoT devices.

Essentially, we design a framework called Multi-Layer Aggregate Verification (MLAV) in order to improve Agriculture 4.0 supply chain management with IoT Blockchain devices.

**Comment by twan-dev** [comment]
Seth has been working on this without moving it to drafting - I've asked him to stop until the ticket is ready.

**Comment by twan-dev** [comment]
Closing because next steps were not approved.
